name: cd

on:
  push:
    branches:
      - "main"

jobs:
  cd:

    strategy:
      matrix:
        conf:
          - name: image-api
            dockerFile: Dockerfile
            manifestFile: ./hew-dev/image/image.yml
            repository: HAL-IAIH-team-F/k8s-hew
    runs-on: ubuntu-latest
    env:
      harborUser: robot$hew

    steps:
      # checkout
      - uses: actions/checkout@v4

      - name: preBuild
        if: ${{ matrix.conf.preDockerBuildCmd }}
        run: ${{ matrix.conf.preDockerBuildCmd }}

      # docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: harbor.kigawa.net
          username: ${{ env.harborUser }}
          password: ${{ secrets.HARBOR_PASS }}

      - uses: docker/build-push-action@v5
        with:
          context: ${{ env.dir }}
          file: ${{ matrix.conf.dockerFile }}
          push: true
          tags: harbor.kigawa.net/private/${{ matrix.conf.name }}:${{ github.ref_name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ env.dockerArg }}

      - name: Update YAML File
        run: |
          yq -i '.spec.template.spec.containers[0].image = "harbor.kigawa.net/private/${{ matrix.conf.name }}:${{ github.ref_name }}-${{ github.sha }}"' \
          ${{ matrix.conf.manifestFile }}

      - name: push
        run: |
          git config user.name githubActions
          git config user.email bot@kigawa.net
          git add .
          git commit --author=. -m "update rev"
          git push
